# COMPONENT_SRCDIRS := src
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := json

# PROJECT_VER:= $(CONFIG_APP_PROJECT_VER)


CFLAGS += -D PROJECT_VER=\""$(CONFIG_APP_PROJECT_VER)"\" -D PROJECT_NAME=\""$(PROJECT_NAME)"\" -D PROJECT_TIME=__TIME__ -D PROJECT_DATE=__DATE__ 