 ; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1]
platform = espressif8266
board = d1
framework = arduino
board_build.mcu = esp8266
; set frequency to 160MHz
; board_build.f_cpu = 160000000L

upload_port = COM39
upload_speed  = 512000

monitor_port = COM39
monitor_speed = 115200